// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Zero Root AI

// Command mission-jsonschema-gen reads a Buf FileDescriptorSet and
// emits a single JSON Schema (Draft 2020-12) document for the
// gibson.mission.v1.MissionDefinition message and its transitive
// types. The schema is consumed by the dashboard's YAML editor for
// inline completion, hover, and validation; the daemon remains the
// authoritative validator at runtime via protovalidate.
//
// Field naming follows protojson (camelCase). Mappings:
//
//	proto message → JSON Schema object (additionalProperties: false)
//	proto enum    → enum: [string-name list], excluding _UNSPECIFIED
//	proto oneof   → oneOf branches per variant
//	proto repeated → JSON Schema array
//	proto map<K,V> → object (with additionalProperties matching V)
//	optional      → field omitted from `required`
//	(buf.validate.field).int32  = { gte: N }   → minimum: N
//	(buf.validate.field).repeated.min_items = N → minItems: N
//	leading proto comment → description
//
// Spec: mission-authoring-cue Requirement 9.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	rootMessage = "gibson.mission.v1.MissionDefinition"
	schemaURI   = "https://json-schema.org/draft/2020-12/schema"
	header      = "// generated by mission-jsonschema-gen — DO NOT EDIT.\n"
)

func main() {
	inputPath := flag.String("input", "", "Buf FileDescriptorSet path")
	outputPath := flag.String("output", "", "JSON Schema output path")
	flag.Parse()
	if *inputPath == "" || *outputPath == "" {
		log.Fatal("both -input and -output are required")
	}
	if err := run(*inputPath, *outputPath); err != nil {
		log.Fatalf("mission-jsonschema-gen: %v", err)
	}
}

func run(inputPath, outputPath string) error {
	fdsBytes, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("read FDS: %w", err)
	}
	fds := &descriptorpb.FileDescriptorSet{}
	if err := proto.Unmarshal(fdsBytes, fds); err != nil {
		return fmt.Errorf("unmarshal FDS: %w", err)
	}
	files, err := protodesc.NewFiles(fds)
	if err != nil {
		return fmt.Errorf("build descriptor index: %w", err)
	}

	// Find the root message descriptor.
	desc, err := files.FindDescriptorByName(protoreflect.FullName(rootMessage))
	if err != nil {
		return fmt.Errorf("locate %s: %w", rootMessage, err)
	}
	rootMD, ok := desc.(protoreflect.MessageDescriptor)
	if !ok {
		return fmt.Errorf("%s is not a message", rootMessage)
	}

	g := &generator{
		files:       files,
		definitions: make(map[string]map[string]any),
		seen:        make(map[string]bool),
	}
	rootSchema := g.messageSchema(rootMD)

	out := map[string]any{
		"$schema":     schemaURI,
		"$id":         "https://gibson.zeroroot.ai/schemas/mission-definition.json",
		"title":       "MissionDefinition",
		"description": "Canonical schema for a gibson mission. Generated from gibson.mission.v1.MissionDefinition.",
	}
	for k, v := range rootSchema {
		out[k] = v
	}
	out["$defs"] = g.definitions

	if err := writeJSON(outputPath, out); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

type generator struct {
	files       *protoregistry.Files
	definitions map[string]map[string]any
	seen        map[string]bool
}

// messageSchema returns the inline schema object for a message,
// also registering nested message types under $defs for reuse.
func (g *generator) messageSchema(md protoreflect.MessageDescriptor) map[string]any {
	schema := map[string]any{
		"type":                 "object",
		"additionalProperties": false,
	}
	if c := commentFor(md); c != "" {
		schema["description"] = c
	}

	properties := map[string]any{}
	required := []string{}

	// Group oneofs first so we can emit oneOf at the message level.
	oneofGroups := map[string][]protoreflect.FieldDescriptor{}
	fields := md.Fields()
	for i := 0; i < fields.Len(); i++ {
		f := fields.Get(i)
		if oneof := f.ContainingOneof(); oneof != nil && !oneof.IsSynthetic() {
			oneofGroups[string(oneof.Name())] = append(oneofGroups[string(oneof.Name())], f)
			continue
		}
		properties[f.JSONName()] = g.fieldSchema(f)
		if isRequired(f) {
			required = append(required, f.JSONName())
		}
	}

	if len(properties) > 0 {
		schema["properties"] = properties
	}
	if len(required) > 0 {
		sort.Strings(required)
		schema["required"] = required
	}

	if len(oneofGroups) > 0 {
		oneofs := []map[string]any{}
		// Iterate in declared order for determinism.
		oos := md.Oneofs()
		for i := 0; i < oos.Len(); i++ {
			oo := oos.Get(i)
			if oo.IsSynthetic() {
				continue
			}
			variants := oneofGroups[string(oo.Name())]
			if len(variants) == 0 {
				continue
			}
			branches := []map[string]any{}
			for _, f := range variants {
				branches = append(branches, map[string]any{
					"required": []string{f.JSONName()},
					"properties": map[string]any{
						f.JSONName(): g.fieldSchema(f),
					},
				})
			}
			oneofs = append(oneofs, map[string]any{
				"oneOf": branches,
			})
		}
		// Compose multiple oneofs via allOf.
		if len(oneofs) == 1 {
			for k, v := range oneofs[0] {
				schema[k] = v
			}
		} else {
			schema["allOf"] = oneofs
		}
	}

	return schema
}

// fieldSchema returns the JSON Schema fragment for a single field.
func (g *generator) fieldSchema(f protoreflect.FieldDescriptor) map[string]any {
	if f.IsMap() {
		valueSchema := g.scalarOrMessageSchema(f.MapValue())
		return map[string]any{
			"type":                 "object",
			"additionalProperties": valueSchema,
			"description":          commentFor(f),
		}
	}
	if f.IsList() {
		items := g.scalarOrMessageSchema(f)
		out := map[string]any{
			"type":  "array",
			"items": items,
		}
		if c := commentFor(f); c != "" {
			out["description"] = c
		}
		applyValidationRules(out, f, true)
		return out
	}
	out := g.scalarOrMessageSchema(f)
	if c := commentFor(f); c != "" {
		out["description"] = c
	}
	applyValidationRules(out, f, false)
	return out
}

// scalarOrMessageSchema returns the value-side schema for a field
// (without any list/map wrapping). Used by fieldSchema.
func (g *generator) scalarOrMessageSchema(f protoreflect.FieldDescriptor) map[string]any {
	switch f.Kind() {
	case protoreflect.BoolKind:
		return map[string]any{"type": "boolean"}
	case protoreflect.StringKind:
		return map[string]any{"type": "string"}
	case protoreflect.BytesKind:
		// JSON Schema represents protobuf bytes as base64 strings.
		return map[string]any{"type": "string", "contentEncoding": "base64"}
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return map[string]any{"type": "integer", "format": "int32"}
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return map[string]any{"type": "integer", "format": "uint32", "minimum": 0}
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return map[string]any{"type": "integer", "format": "int64"}
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return map[string]any{"type": "integer", "format": "uint64", "minimum": 0}
	case protoreflect.FloatKind:
		return map[string]any{"type": "number", "format": "float"}
	case protoreflect.DoubleKind:
		return map[string]any{"type": "number", "format": "double"}
	case protoreflect.EnumKind:
		return g.enumSchema(f.Enum())
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return g.messageRef(f.Message())
	default:
		return map[string]any{}
	}
}

// enumSchema emits an enum schema with the named values (excluding
// the _UNSPECIFIED sentinel). Description picked up from the enum's
// leading comment.
func (g *generator) enumSchema(ed protoreflect.EnumDescriptor) map[string]any {
	values := []string{}
	for i := 0; i < ed.Values().Len(); i++ {
		ev := ed.Values().Get(i)
		name := string(ev.Name())
		if strings.HasSuffix(name, "_UNSPECIFIED") {
			continue
		}
		values = append(values, name)
	}
	out := map[string]any{"type": "string", "enum": values}
	if c := commentFor(ed); c != "" {
		out["description"] = c
	}
	return out
}

// messageRef registers (if needed) the message under $defs and
// returns a $ref pointing to it. Well-known types are flattened
// directly.
func (g *generator) messageRef(md protoreflect.MessageDescriptor) map[string]any {
	switch string(md.FullName()) {
	case "google.protobuf.Duration":
		return map[string]any{
			"type":        "string",
			"description": "Duration in protobuf Duration format (e.g. \"3.5s\", \"1h30m\").",
		}
	case "google.protobuf.Timestamp":
		return map[string]any{
			"type":        "string",
			"format":      "date-time",
			"description": "RFC 3339 timestamp.",
		}
	}

	defName := defNameOf(md)
	if !g.seen[defName] {
		g.seen[defName] = true
		// Defensive: register an empty placeholder before recursing
		// to handle self-referential types cleanly.
		g.definitions[defName] = map[string]any{}
		g.definitions[defName] = g.messageSchema(md)
	}
	return map[string]any{"$ref": "#/$defs/" + defName}
}

// defNameOf returns a JSON-Schema-safe def key for a message. Uses
// the unqualified message name for readability; collisions across
// packages get disambiguated by appending a short package hash.
func defNameOf(md protoreflect.MessageDescriptor) string {
	full := string(md.FullName())
	parts := strings.Split(full, ".")
	return parts[len(parts)-1]
}

// applyValidationRules reads (buf.validate.field).* extensions and
// stamps the equivalent JSON Schema constraint into out.
func applyValidationRules(out map[string]any, f protoreflect.FieldDescriptor, isList bool) {
	opts, ok := f.Options().(*descriptorpb.FieldOptions)
	if !ok || opts == nil {
		return
	}
	rulesAny := proto.GetExtension(opts, validate.E_Field)
	rules, ok := rulesAny.(*validate.FieldRules)
	if !ok || rules == nil {
		return
	}
	if isList {
		if rep := rules.GetRepeated(); rep != nil {
			if rep.MinItems != nil {
				out["minItems"] = *rep.MinItems
			}
			if rep.MaxItems != nil {
				out["maxItems"] = *rep.MaxItems
			}
		}
		return
	}
	switch r := rules.Type.(type) {
	case *validate.FieldRules_Int32:
		if r.Int32 != nil {
			if r.Int32.GetGte() != 0 || hasGte(r.Int32) {
				out["minimum"] = r.Int32.GetGte()
			}
			if r.Int32.GetLte() != 0 || hasLte(r.Int32) {
				out["maximum"] = r.Int32.GetLte()
			}
		}
	case *validate.FieldRules_Int64:
		if r.Int64 != nil {
			if hasGteI64(r.Int64) {
				out["minimum"] = r.Int64.GetGte()
			}
			if hasLteI64(r.Int64) {
				out["maximum"] = r.Int64.GetLte()
			}
		}
	case *validate.FieldRules_String_:
		if r.String_ != nil {
			if r.String_.MinLen != nil {
				out["minLength"] = *r.String_.MinLen
			}
			if r.String_.MaxLen != nil {
				out["maxLength"] = *r.String_.MaxLen
			}
			if r.String_.Pattern != nil {
				out["pattern"] = *r.String_.Pattern
			}
		}
	}
}

func hasGte(r *validate.Int32Rules) bool {
	if r == nil {
		return false
	}
	switch r.LessThan.(type) {
	default:
	}
	return r.GreaterThan != nil // safe enough
}

func hasLte(r *validate.Int32Rules) bool {
	if r == nil {
		return false
	}
	return r.LessThan != nil
}

func hasGteI64(r *validate.Int64Rules) bool {
	if r == nil {
		return false
	}
	return r.GreaterThan != nil
}

func hasLteI64(r *validate.Int64Rules) bool {
	if r == nil {
		return false
	}
	return r.LessThan != nil
}

// commentFor returns the trimmed leading comment of a descriptor,
// or "" if absent.
func commentFor(d protoreflect.Descriptor) string {
	srcLoc := d.ParentFile().SourceLocations().ByDescriptor(d)
	c := strings.TrimSpace(srcLoc.LeadingComments)
	if c == "" {
		return ""
	}
	// Strip the leading comment markers and join lines.
	lines := strings.Split(c, "\n")
	for i, l := range lines {
		l = strings.TrimSpace(l)
		l = strings.TrimPrefix(l, "//")
		l = strings.TrimSpace(l)
		lines[i] = l
	}
	return strings.TrimSpace(strings.Join(lines, " "))
}

// isRequired checks the proto3 required-ness rule. With proto3,
// non-optional scalars are always present; we only mark fields as
// required when buf-validate flags them or they're message-typed
// without explicit presence markers. For our schema we keep the
// list conservative — only mark as required when buf-validate
// declares required=true.
func isRequired(f protoreflect.FieldDescriptor) bool {
	opts, ok := f.Options().(*descriptorpb.FieldOptions)
	if !ok || opts == nil {
		return false
	}
	rulesAny := proto.GetExtension(opts, validate.E_Field)
	rules, ok := rulesAny.(*validate.FieldRules)
	if !ok || rules == nil {
		return false
	}
	return rules.Required != nil && *rules.Required
}

// writeJSON marshals out to indent=2 JSON and writes with a
// generated-by header (for human discoverability — JSON parsers
// ignore the leading comment after the header is stripped).
// Note: pure JSON files cannot carry comments, so we write the
// generator banner alongside the file as a sibling .gen-banner
// for tooling that wants it. The JSON itself stays clean.
func writeJSON(path string, v any) error {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	b = append(b, '\n')
	return os.WriteFile(path, b, 0o644)
}

var _ = header // reserved for future header emission via sibling file
