// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: taxonomy/core.yaml
// Taxonomy Version: 4.1.0

package taxonomy

// ParentRelationship defines how a child node relates to its parent.
type ParentRelationship struct {
	// ChildType is the node type name (e.g., "port")
	ChildType string
	// ParentType is the parent node type name (e.g., "host")
	ParentType string
	// RefField is the field on the child that holds the parent UUID (e.g., "host_id")
	RefField string
	// ParentField is the field on the parent to match against (always "id")
	ParentField string
	// Relationship is the Neo4j relationship type (e.g., "HAS_PORT")
	Relationship string
	// Required indicates if the parent is mandatory
	Required bool
}

// ParentRelationships maps child node types to their parent relationship config.
var ParentRelationships = map[string]ParentRelationship{
	"mission_run": {
		ChildType:    "mission_run",
		ParentType:   "mission",
		RefField:     "mission_id",
		ParentField:  "id",
		Relationship: "BELONGS_TO",
		Required:     true,
	},
	"tool_execution": {
		ChildType:    "tool_execution",
		ParentType:   "agent_run",
		RefField:     "agent_run_id",
		ParentField:  "id",
		Relationship: "USED_TOOL",
		Required:     true,
	},
	"subdomain": {
		ChildType:    "subdomain",
		ParentType:   "domain",
		RefField:     "domain_id",
		ParentField:  "id",
		Relationship: "HAS_SUBDOMAIN",
		Required:     true,
	},
	"port": {
		ChildType:    "port",
		ParentType:   "host",
		RefField:     "host_id",
		ParentField:  "id",
		Relationship: "HAS_PORT",
		Required:     true,
	},
	"service": {
		ChildType:    "service",
		ParentType:   "port",
		RefField:     "port_id",
		ParentField:  "id",
		Relationship: "RUNS_SERVICE",
		Required:     true,
	},
	"endpoint": {
		ChildType:    "endpoint",
		ParentType:   "service",
		RefField:     "service_id",
		ParentField:  "id",
		Relationship: "HAS_ENDPOINT",
		Required:     true,
	},
	"evidence": {
		ChildType:    "evidence",
		ParentType:   "finding",
		RefField:     "finding_id",
		ParentField:  "id",
		Relationship: "HAS_EVIDENCE",
		Required:     true,
	},
	"compliance_signal": {
		ChildType:    "compliance_signal",
		ParentType:   "agent_run",
		RefField:     "agent_run_id",
		ParentField:  "id",
		Relationship: "EMITTED_SIGNAL",
		Required:     false,
	},
}

// RootNodeTypes lists node types that have no parent (can attach to MissionRun).
var RootNodeTypes = []string{
	"mission",
	"agent_run",
	"llm_call",
	"domain",
	"host",
	"technology",
	"certificate",
	"finding",
	"technique",
	"scope",
	"credential",
	"account",
}

// IsRootNodeType returns true if the given node type is a root type (no parent).
func IsRootNodeType(nodeType string) bool {
	for _, rt := range RootNodeTypes {
		if rt == nodeType {
			return true
		}
	}
	return false
}

// GetParentRelationship returns the parent relationship config for a child type.
// Returns nil if the type has no parent (is a root type).
func GetParentRelationship(childType string) *ParentRelationship {
	if rel, ok := ParentRelationships[childType]; ok {
		return &rel
	}
	return nil
}
