// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: taxonomy/core.yaml
// Taxonomy Version: 4.1.0

package graphrag

// ==================== NODE TYPE CONSTANTS ====================

// Node type constants for compile-time safety.
const (
	// NodeTypeMission is the "mission" node type.
	NodeTypeMission = "mission"
	// NodeTypeMissionRun is the "mission_run" node type.
	NodeTypeMissionRun = "mission_run"
	// NodeTypeAgentRun is the "agent_run" node type.
	NodeTypeAgentRun = "agent_run"
	// NodeTypeToolExecution is the "tool_execution" node type.
	NodeTypeToolExecution = "tool_execution"
	// NodeTypeLlmCall is the "llm_call" node type.
	NodeTypeLlmCall = "llm_call"
	// NodeTypeDomain is the "domain" node type.
	NodeTypeDomain = "domain"
	// NodeTypeSubdomain is the "subdomain" node type.
	NodeTypeSubdomain = "subdomain"
	// NodeTypeHost is the "host" node type.
	NodeTypeHost = "host"
	// NodeTypePort is the "port" node type.
	NodeTypePort = "port"
	// NodeTypeService is the "service" node type.
	NodeTypeService = "service"
	// NodeTypeEndpoint is the "endpoint" node type.
	NodeTypeEndpoint = "endpoint"
	// NodeTypeTechnology is the "technology" node type.
	NodeTypeTechnology = "technology"
	// NodeTypeCertificate is the "certificate" node type.
	NodeTypeCertificate = "certificate"
	// NodeTypeFinding is the "finding" node type.
	NodeTypeFinding = "finding"
	// NodeTypeEvidence is the "evidence" node type.
	NodeTypeEvidence = "evidence"
	// NodeTypeTechnique is the "technique" node type.
	NodeTypeTechnique = "technique"
	// NodeTypeComplianceSignal is the "compliance_signal" node type.
	NodeTypeComplianceSignal = "compliance_signal"
	// NodeTypeScope is the "scope" node type.
	NodeTypeScope = "scope"
	// NodeTypeCredential is the "credential" node type.
	NodeTypeCredential = "credential"
	// NodeTypeAccount is the "account" node type.
	NodeTypeAccount = "account"
)

// ==================== RELATIONSHIP TYPE CONSTANTS ====================

// Relationship type constants for compile-time safety.
const (
	// RelTypeUSEDTOOL is the "USED_TOOL" relationship type.
	RelTypeUSEDTOOL = "USED_TOOL"
	// RelTypeDELEGATEDTO is the "DELEGATED_TO" relationship type.
	RelTypeDELEGATEDTO = "DELEGATED_TO"
	// RelTypeEMITTEDSIGNAL is the "EMITTED_SIGNAL" relationship type.
	RelTypeEMITTEDSIGNAL = "EMITTED_SIGNAL"
	// RelTypeTRIGGERED is the "TRIGGERED" relationship type.
	RelTypeTRIGGERED = "TRIGGERED"
	// RelTypeHASSUBDOMAIN is the "HAS_SUBDOMAIN" relationship type.
	RelTypeHASSUBDOMAIN = "HAS_SUBDOMAIN"
	// RelTypeRESOLVESTO is the "RESOLVES_TO" relationship type.
	RelTypeRESOLVESTO = "RESOLVES_TO"
	// RelTypeHASPORT is the "HAS_PORT" relationship type.
	RelTypeHASPORT = "HAS_PORT"
	// RelTypeRUNSSERVICE is the "RUNS_SERVICE" relationship type.
	RelTypeRUNSSERVICE = "RUNS_SERVICE"
	// RelTypeHASENDPOINT is the "HAS_ENDPOINT" relationship type.
	RelTypeHASENDPOINT = "HAS_ENDPOINT"
	// RelTypeUSESTECHNOLOGY is the "USES_TECHNOLOGY" relationship type.
	RelTypeUSESTECHNOLOGY = "USES_TECHNOLOGY"
	// RelTypeSERVESCERTIFICATE is the "SERVES_CERTIFICATE" relationship type.
	RelTypeSERVESCERTIFICATE = "SERVES_CERTIFICATE"
	// RelTypeAFFECTS is the "AFFECTS" relationship type.
	RelTypeAFFECTS = "AFFECTS"
	// RelTypeHASEVIDENCE is the "HAS_EVIDENCE" relationship type.
	RelTypeHASEVIDENCE = "HAS_EVIDENCE"
	// RelTypeUSESTECHNIQUE is the "USES_TECHNIQUE" relationship type.
	RelTypeUSESTECHNIQUE = "USES_TECHNIQUE"
	// RelTypeLEADSTO is the "LEADS_TO" relationship type.
	RelTypeLEADSTO = "LEADS_TO"
)

// ==================== CORE TYPES MAP ====================

// CoreTypes is a set of all core (validated) node types.
var CoreTypes = map[string]bool{
	"mission":           true,
	"mission_run":       true,
	"agent_run":         true,
	"tool_execution":    true,
	"llm_call":          true,
	"domain":            true,
	"subdomain":         true,
	"host":              true,
	"port":              true,
	"service":           true,
	"endpoint":          true,
	"technology":        true,
	"certificate":       true,
	"finding":           true,
	"evidence":          true,
	"technique":         true,
	"compliance_signal": true,
	"scope":             true,
	"credential":        true,
	"account":           true,
}

// IsCoreType returns true if the node type is a core (validated) type.
func IsCoreType(nodeType string) bool {
	return CoreTypes[nodeType]
}

// ==================== PARENT REQUIREMENTS ====================

// ParentRequirement defines the parent relationship for a node type.
type ParentRequirement struct {
	ParentType   string
	Relationship string
	Required     bool
}

// ParentRequirements maps node types to their parent requirements.
var ParentRequirements = map[string]ParentRequirement{
	"mission_run": {
		ParentType:   "mission",
		Relationship: "BELONGS_TO",
		Required:     true,
	},
	"tool_execution": {
		ParentType:   "agent_run",
		Relationship: "USED_TOOL",
		Required:     true,
	},
	"subdomain": {
		ParentType:   "domain",
		Relationship: "HAS_SUBDOMAIN",
		Required:     true,
	},
	"port": {
		ParentType:   "host",
		Relationship: "HAS_PORT",
		Required:     true,
	},
	"service": {
		ParentType:   "port",
		Relationship: "RUNS_SERVICE",
		Required:     true,
	},
	"endpoint": {
		ParentType:   "service",
		Relationship: "HAS_ENDPOINT",
		Required:     true,
	},
	"evidence": {
		ParentType:   "finding",
		Relationship: "HAS_EVIDENCE",
		Required:     true,
	},
	"compliance_signal": {
		ParentType:   "agent_run",
		Relationship: "EMITTED_SIGNAL",
		Required:     false,
	},
}

// GetParentRequirement returns the parent requirement for a node type.
func GetParentRequirement(nodeType string) (ParentRequirement, bool) {
	req, ok := ParentRequirements[nodeType]
	return req, ok
}

// ==================== ALL NODE TYPES ====================

// AllNodeTypes is a list of all core node type names.
var AllNodeTypes = []string{
	"mission",
	"mission_run",
	"agent_run",
	"tool_execution",
	"llm_call",
	"domain",
	"subdomain",
	"host",
	"port",
	"service",
	"endpoint",
	"technology",
	"certificate",
	"finding",
	"evidence",
	"technique",
	"compliance_signal",
	"scope",
	"credential",
	"account",
}

// ==================== ALL RELATIONSHIP TYPES ====================

// AllRelationshipTypes is a list of all core relationship type names.
var AllRelationshipTypes = []string{
	"USED_TOOL",
	"DELEGATED_TO",
	"EMITTED_SIGNAL",
	"TRIGGERED",
	"HAS_SUBDOMAIN",
	"RESOLVES_TO",
	"HAS_PORT",
	"RUNS_SERVICE",
	"HAS_ENDPOINT",
	"USES_TECHNOLOGY",
	"SERVES_CERTIFICATE",
	"AFFECTS",
	"HAS_EVIDENCE",
	"USES_TECHNIQUE",
	"LEADS_TO",
}
