// Code generated by taxonomy-gen from taxonomy YAML. DO NOT EDIT.
// Source: taxonomy/core.yaml
// Taxonomy Version: 4.1.0

package graphrag

import (
	"github.com/google/uuid"
	taxonomypb "github.com/zeroroot-ai/sdk/api/gen/taxonomy/v1"
)

// ==================== NODE CREATION HELPERS ====================
//
// These helpers auto-generate UUIDs and set up parent relationships.
// Use these instead of manually creating protobuf messages.
//
// Root types (no parent):
//   - NewHost(ip string) *taxonomypb.Host
//   - NewDomain(name string) *taxonomypb.Domain
//   - etc.
//
// Child types (has parent):
//   - NewPort(parent *taxonomypb.Host, number int32, protocol string) *taxonomypb.Port
//   - NewService(parent *taxonomypb.Port, name string) *taxonomypb.Service
//   - etc.
//
// All helpers:
//   1. Generate a UUID and assign to Id field
//   2. Set required properties
//   3. For child types: copy parent.Id to the parent reference field
//   4. Panic if parent.Id is nil (must use NewXxx() or set Id manually)
//

// NewMission creates a Mission with auto-generated UUID.
func NewMission(name string, target string) *taxonomypb.Mission {
	id := uuid.New().String()
	return &taxonomypb.Mission{
		Id:     id,
		Name:   name,
		Target: target,
	}
}

// NewMissionRun creates a MissionRun linked to parent Mission.
// Panics if parent.Id is empty.
func NewMissionRun(parent *taxonomypb.Mission, run_number int32, actor_id string, actor_tenant_id string, mission_yaml_digest string) *taxonomypb.MissionRun {
	if parent.Id == "" {
		panic("parent Mission must have Id set - use NewMission() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.MissionRun{
		Id:                id,
		ParentMissionId:   parent.Id,
		RunNumber:         run_number,
		ActorId:           actor_id,
		ActorTenantId:     actor_tenant_id,
		MissionYamlDigest: mission_yaml_digest,
	}
}

// NewAgentRun creates a AgentRun with auto-generated UUID.
func NewAgentRun(agent_name string, actor_id string, actor_tenant_id string, component_name string, component_version string, system_owned bool) *taxonomypb.AgentRun {
	id := uuid.New().String()
	return &taxonomypb.AgentRun{
		Id:               id,
		AgentName:        agent_name,
		ActorId:          actor_id,
		ActorTenantId:    actor_tenant_id,
		ComponentName:    component_name,
		ComponentVersion: component_version,
		SystemOwned:      system_owned,
	}
}

// NewToolExecution creates a ToolExecution linked to parent AgentRun.
// Panics if parent.Id is empty.
func NewToolExecution(parent *taxonomypb.AgentRun, tool_name string, actor_id string, actor_tenant_id string, component_name string, component_version string, system_owned bool) *taxonomypb.ToolExecution {
	if parent.Id == "" {
		panic("parent AgentRun must have Id set - use NewAgentRun() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.ToolExecution{
		Id:               id,
		ParentAgentRunId: parent.Id,
		ToolName:         tool_name,
		ActorId:          actor_id,
		ActorTenantId:    actor_tenant_id,
		ComponentName:    component_name,
		ComponentVersion: component_version,
		SystemOwned:      system_owned,
	}
}

// NewLlmCall creates a LlmCall with auto-generated UUID.
func NewLlmCall(model string, actor_id string, actor_tenant_id string, component_name string, component_version string, model_id string) *taxonomypb.LlmCall {
	id := uuid.New().String()
	return &taxonomypb.LlmCall{
		Id:               id,
		Model:            model,
		ActorId:          actor_id,
		ActorTenantId:    actor_tenant_id,
		ComponentName:    component_name,
		ComponentVersion: component_version,
		ModelId:          model_id,
	}
}

// NewDomain creates a Domain with auto-generated UUID.
func NewDomain(name string) *taxonomypb.Domain {
	id := uuid.New().String()
	return &taxonomypb.Domain{
		Id:   id,
		Name: name,
	}
}

// NewSubdomain creates a Subdomain linked to parent Domain.
// Panics if parent.Id is empty.
func NewSubdomain(parent *taxonomypb.Domain, name string) *taxonomypb.Subdomain {
	if parent.Id == "" {
		panic("parent Domain must have Id set - use NewDomain() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Subdomain{
		Id:             id,
		ParentDomainId: parent.Id,
		Name:           name,
	}
}

// NewHost creates a Host with auto-generated UUID.
func NewHost() *taxonomypb.Host {
	id := uuid.New().String()
	return &taxonomypb.Host{
		Id: id,
	}
}

// NewPort creates a Port linked to parent Host.
// Panics if parent.Id is empty.
func NewPort(parent *taxonomypb.Host, number int32, protocol string) *taxonomypb.Port {
	if parent.Id == "" {
		panic("parent Host must have Id set - use NewHost() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Port{
		Id:           id,
		ParentHostId: parent.Id,
		Number:       number,
		Protocol:     protocol,
	}
}

// NewService creates a Service linked to parent Port.
// Panics if parent.Id is empty.
func NewService(parent *taxonomypb.Port, name string) *taxonomypb.Service {
	if parent.Id == "" {
		panic("parent Port must have Id set - use NewPort() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Service{
		Id:           id,
		ParentPortId: parent.Id,
		Name:         name,
	}
}

// NewEndpoint creates a Endpoint linked to parent Service.
// Panics if parent.Id is empty.
func NewEndpoint(parent *taxonomypb.Service, url string) *taxonomypb.Endpoint {
	if parent.Id == "" {
		panic("parent Service must have Id set - use NewService() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Endpoint{
		Id:              id,
		ParentServiceId: parent.Id,
		Url:             url,
	}
}

// NewTechnology creates a Technology with auto-generated UUID.
func NewTechnology(name string) *taxonomypb.Technology {
	id := uuid.New().String()
	return &taxonomypb.Technology{
		Id:   id,
		Name: name,
	}
}

// NewCertificate creates a Certificate with auto-generated UUID.
func NewCertificate() *taxonomypb.Certificate {
	id := uuid.New().String()
	return &taxonomypb.Certificate{
		Id: id,
	}
}

// NewFinding creates a Finding with auto-generated UUID.
func NewFinding(title string, severity string) *taxonomypb.Finding {
	id := uuid.New().String()
	return &taxonomypb.Finding{
		Id:       id,
		Title:    title,
		Severity: severity,
	}
}

// NewEvidence creates a Evidence linked to parent Finding.
// Panics if parent.Id is empty.
func NewEvidence(parent *taxonomypb.Finding, type_ string) *taxonomypb.Evidence {
	if parent.Id == "" {
		panic("parent Finding must have Id set - use NewFinding() or set Id manually")
	}
	id := uuid.New().String()
	return &taxonomypb.Evidence{
		Id:              id,
		ParentFindingId: parent.Id,
		Type:            type_,
	}
}

// NewTechnique creates a Technique with auto-generated UUID.
func NewTechnique(technique_id string, name string) *taxonomypb.Technique {
	id := uuid.New().String()
	return &taxonomypb.Technique{
		Id:          id,
		TechniqueId: technique_id,
		Name:        name,
	}
}

// NewComplianceSignal creates a ComplianceSignal linked to parent AgentRun.
// Panics if parent.Id is empty.
func NewComplianceSignal(parent *taxonomypb.AgentRun, signal_id string, actor_id string, actor_tenant_id string, caller_component string, caller_component_version string, target_component string, target_component_version string, system_owned bool, action string, effect string, resource_type string, decision string, success bool, latency_ms int64, occurred_at int64) *taxonomypb.ComplianceSignal {
	if parent.Id == "" {
		panic("parent AgentRun must have Id set - use NewAgentRun() or set Id manually")
	}
	id := uuid.New().String()
	_parentId := parent.Id
	return &taxonomypb.ComplianceSignal{
		Id:                     id,
		AgentRunId:             &_parentId,
		SignalId:               signal_id,
		ActorId:                actor_id,
		ActorTenantId:          actor_tenant_id,
		CallerComponent:        caller_component,
		CallerComponentVersion: caller_component_version,
		TargetComponent:        target_component,
		TargetComponentVersion: target_component_version,
		SystemOwned:            system_owned,
		Action:                 action,
		Effect:                 effect,
		ResourceType:           resource_type,
		Decision:               decision,
		Success:                success,
		LatencyMs:              latency_ms,
		OccurredAt:             occurred_at,
	}
}

// NewScope creates a Scope with auto-generated UUID.
func NewScope(scope_id string) *taxonomypb.Scope {
	id := uuid.New().String()
	return &taxonomypb.Scope{
		Id:      id,
		ScopeId: scope_id,
	}
}

// NewCredential creates a Credential with auto-generated UUID.
func NewCredential(hash string) *taxonomypb.Credential {
	id := uuid.New().String()
	return &taxonomypb.Credential{
		Id:   id,
		Hash: hash,
	}
}

// NewAccount creates a Account with auto-generated UUID.
func NewAccount(provider string, subject string) *taxonomypb.Account {
	id := uuid.New().String()
	return &taxonomypb.Account{
		Id:       id,
		Provider: provider,
		Subject:  subject,
	}
}
